// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBonoMpYYI4K6Px0buso4LX1LTFXkV50Q4',
    appId: '1:121435988107:web:dec48fc0233d5014d7748e',
    messagingSenderId: '121435988107',
    projectId: 'tesis-9f72a',
    authDomain: 'tesis-9f72a.firebaseapp.com',
    storageBucket: 'tesis-9f72a.appspot.com',
    measurementId: 'G-RB9934XDN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI3rrByb4kVWeurvDhaLBQKeDYzCbKTe4',
    appId: '1:121435988107:android:ce2b79020378aa5cd7748e',
    messagingSenderId: '121435988107',
    projectId: 'tesis-9f72a',
    storageBucket: 'tesis-9f72a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXuFxxfZzmjYacQMf_lutBP9nx29BQFV4',
    appId: '1:121435988107:ios:afee150a349bf95ad7748e',
    messagingSenderId: '121435988107',
    projectId: 'tesis-9f72a',
    storageBucket: 'tesis-9f72a.appspot.com',
    iosClientId: '121435988107-dhp9hvurvrpm7tb688581e2lnd3phpnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.atelRedesTelecomProt',
  );
}
